docker_image:
   image: docker:latest
   stage: build
   tags: 
     - docker
   script:
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
     - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
     - docker push $CI_REGISTRY_IMAGE:latest

flake:
   image: $CI_REGISTRY_IMAGE:latest
   stage: build
   tags:
      - docker
   script:
      - flake8 .

unit_tests:
   image: $CI_REGISTRY_IMAGE:latest
   stage: test
   tags:
      - docker
   script:
      # Install dolfin-y package
      - pip3 install .
      # Run Python unit tests (serial)
      - python3 -m pytest -vsx test/.
      # Run Python unit tests (parallel)
      - mpirun -n 3 python3 -u -m pytest -vsx test/.

demos:
   image: $CI_REGISTRY_IMAGE:latest
   stage: test
   tags:
      - docker
   script:
      # Install dolfin-y package
      - pip3 install .
      # Run bingham demo
      - cd demo/bingham && python3 bingham_block.py