stages:
   - lint
   - build
   - test
   - release

default:
   tags:
      - docker

variables:
   CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_REF_SLUG
   CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

# jobs

flake8:
   stage: lint
   image: pipelinecomponents/flake8:latest
   script:
      - flake8 --verbose .

docker_image:
   image: docker:latest
   stage: build
   script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build --no-cache --pull --build-arg DOLFINY_BUILD_TYPE=Release -t $CONTAINER_TEST_IMAGE .
      - docker push $CONTAINER_TEST_IMAGE

pytest:
   image: $CONTAINER_TEST_IMAGE
   stage: test
   script:
      # Install dolfin-y package
      - pip3 install .
      # Run Python unit tests (parallel)
      - mpirun -n 2 python3 -u -m pytest -vsx test/.
      - mpirun -n 3 python3 -u -m pytest -vsx test/.
      - mpirun -n 4 python3 -u -m pytest -vsx test/.
      # Run Python unit tests (serial)
      - python3 -m pytest -vsx test/.

demos:
   image: $CONTAINER_TEST_IMAGE
   stage: test
   script:
      # Install dolfin-y package
      - pip3 install .
      # Run bingham demo (parallel)
      - cd demo/bingham && mpirun -n 2 python3 bingham_block.py
   artifacts:
      name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-artifacts"
      paths:
         - demo/*/*
      expire_in: 1 week

docker_latest:
   image: docker:latest
   stage: release
   script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker pull $CONTAINER_TEST_IMAGE
      - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
      - docker push $CONTAINER_RELEASE_IMAGE
   only:
      - master
