before_script:
	- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
 
docker_image:
	stage: build
	tags: 
	  - docker
	script:
	  - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
	  - docker push $CI_REGISTRY_IMAGE:latest
