version: 2.1

install-python-components: &install-python-components
  name: Install FEniCS Python components
  command: |
            pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
            pip3 install git+https://github.com/FEniCS/ufl.git --upgrade
            pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
            rm -rf /usr/local/include/dolfinx /usr/local/include/dolfinx.h

build-dolfinx-cpp: &build-dolfinx-cpp
  name: Build dolfinx cpp
  command: |
            git clone --branch michal/meshtags-io https://github.com/FEniCS/dolfinx.git
            cd dolfinx
            mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Developer ../cpp/
            make -j3 install

build-dolfinx-python: &build-dolfinx-python
  name: Build dolfin-x python interface
  command: |
    cd dolfinx/python
    pip3 -v install . --user

jobs:
  build:
    docker:
      - image: dolfinx/dev-env-real
    steps:
      - checkout
      - run:
          name: Flake8
          command: |
            flake8 .
      - run: *install-python-components
      - run: *build-dolfinx-cpp
      - run: *build-dolfinx-python
      - run:
          name: Install dolfin-y package
          command: |
            pip3 install .
      - run:
          name: Run Python unit tests (serial)
          command: |
            python3 -m pytest -vsx test/.
      - run:
          name: Run Python unit tests (perallel)
          command: |
            mpirun -n 2 python3 -m pytest -vsx test/.
      - run:
          name: Run bingham demo
          command: |
            cd demo/bingham
            python3 plain_bingham_block.py

workflows:
  build-and-test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
